"""add naming pattern, publish endpoint and public url

Revision ID: a2df56007c76
Revises: f8cd439d47f7
Create Date: 2026-09-11 15:23:51.096904

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a2df56007c76"
down_revision: str | Sequence[str] | None = "f8cd439d47f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("mirror_sets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("publish_endpoint", sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column("public_url", sa.String(length=512), nullable=True))
        # Sets that already exist were created under the original convention, so
        # that is what they keep; SQLite also needs a server default to add a
        # NOT NULL column to a table with rows in it.
        batch_op.add_column(
            sa.Column(
                "mirror_pattern",
                sa.String(length=64),
                nullable=False,
                server_default="{set}-{suite}-{component}",
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("mirror_sets", schema=None) as batch_op:
        batch_op.drop_column("mirror_pattern")
        batch_op.drop_column("public_url")
        batch_op.drop_column("publish_endpoint")

    # ### end Alembic commands ###
