"""add download progress to job steps

Revision ID: 1d98f4a90784
Revises: acaffe887f68
Create Date: 2026-09-11 10:46:53.834126

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d98f4a90784"
down_revision: str | Sequence[str] | None = "acaffe887f68"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_steps", schema=None) as batch_op:
        batch_op.add_column(sa.Column("total_bytes", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("remaining_bytes", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("total_packages", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("remaining_packages", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_steps", schema=None) as batch_op:
        batch_op.drop_column("remaining_packages")
        batch_op.drop_column("total_packages")
        batch_op.drop_column("remaining_bytes")
        batch_op.drop_column("total_bytes")

    # ### end Alembic commands ###
